---
#- name: Will this work?
#  hosts: localhost
#  connection: ansible.builtin.local
#  gather_facts: false
#
#  vars:
#      tobuild: present   # present or absent
#
#  tasks:
- name: Setup Minecraft Server
  ansible.builtin.import_playbook: minecraft.yml
  when: tobuild == "present"

- name: Rip out Minecraft Server
  ansible.builtin.import_playbook: minecraft-taredown.yml
  when: tobuild ==  "absent"
