---
- name: Remove minecraft server
  hosts: localhost
  connection: ansible.builtin.local
  gather_facts: false

  vars:
    mcstate: absent

  tasks:
    - name: Remove Minecraft server container
      community.docker.docker_container:
        name: minecraft
        image: itzg/minecraft-server:latest
        state: "{{ mcstate }}"
        restart_policy: unless-stopped
        published_ports:
          - "25565:25565"
        volumes:
          - /opt/minecraft:/data
        env:
          EULA: "TRUE"
          TYPE: "PAPER"
          MEMORY: "2G"
          MOTD: "Planet Express Minecraft Server"
          DIFFICULTY: "normal"
          MAX_PLAYERS: "10"


    - name: Remove Minecraft data directory
      become: true
      ansible.builtin.file:
        path: /opt/minecraft/
        state: absent
