---
- name: common linux tasks
  hosts: planetexpress
  gather_facts: true
  connection: ansible.builtin.ssh   # global setting, easily overridden per host basis in the inventory

  tasks:

### prechecks

    # I want to ensure that what is included in the hosts is ONLY debian / ubuntu
    - name: Ensure OS is Debian or Ubuntu
      ansible.builtin.assert:
        that:
          #- ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
          - ansible_facts.distribution == "Debian" or ansible_facts.distribution == "Ubuntu"
        fail_msg: "This host is {{ ansible_distribution }}. Only Debian and Ubuntu are allowed."
        success_msg: "Host OS is supported."


    # I want to ensure that the target systems have X amount of RAM
    - name: Fail if this machine lacks sufficient RAM
      ansible.builtin.assert:
        that:
          - ansible_memtotal_mb >= 10
          # ansible_facts.memtotal_mb >= 10
        fail_msg: >
          This machine does not have sufficient RAM to run Wednesday morning review.
          Required RAM is 10 MB but this machine only has {{ ansible_memtotal_mb }} MB.
    

    # I want to ensure that the target system has N cores available
    - name: Ensure that the system has at least 2 cores
      ansible.builtin.assert:
        that:
          - ansible_processor_cores > = 2
        fail_msg: "This system only has {{ ansible_processor_cores }} when 2 or more are required"


    # I want to ensure that I am not logged in as root
    - name: Ensure remote user is non root
      ansible.builtin.assert:
        that:
          - ansible_user_uid != 0
        fail_msg: 'the remote user should be a non root user'


### Cha cha cha chaaaannngeeessss

    - name: Create i-was-here directory
      ansible.builtin.file:
        path: /tmp/i-was-here/
        state: directory    # directory, file, absent
        mode: "0755"  # owner group others
                      # r = 4
                      # w = 2
                      # x = 1
                      #
                      # 0 ---
                      # 1 --x
                      # 5 r-x
                      # 7 rwx

    - name: Create a file
      ansible.builtin.file:
        path: /tmp/i-was-here/zach.txt
        state: touch   # directory, file, absent


    - name: Create a text file
      ansible.builtin.copy:
        content: "Ansible was here on {{ now() }}"
        dest: /tmp/i-was-here/ansible.txt
        mode: "0644"
